name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: self-hosted
    name: Lint PHP Files
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Lint PHP files
        run: |
          for file in $(find . -name '*.php'); do
            php -l $file;
          done

  build:
    runs-on: self-hosted
    name: Build Docker Image
    needs: lint  # Ajout de la dépendance au job lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t whythem/nginx:latest .

  push:
    runs-on: self-hosted
    name: Push to DockerHub
    needs: build  # Ce job ne s'exécute qu'après le build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: |
          docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password "${{ secrets.DOCKER_HUB_PASSWORD }}"
      
      - name: Push Docker Image
        run: |
          docker push whythem/nginx:latest

  deploy:
      name: Deploy to Remote Server
      runs-on: [self-hosted]
      needs: push
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
  
        - name: Pull Docker images and start containers
          run: |
            if [ "$(docker ps -q -f name=nginx-SSH)" ]; then
                echo "Container 'nginx' is running. Stopping and removing it."
                docker stop nginx-SSH
                docker rm nginx-SSH
            else
                echo "Container 'nginx' is not running."
            fi
            ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
              docker pull whythem/nginx:latest
              docker run -d --name nginx-SSH -p 80:80 whythem/nginx:latest
            EOF
